=== Cheikh785/Gestion_fichier_xml/xml/exo6.dtd
<!ELEMENT examen (classe, matiere, prof, titre, date, Exercice, Exercice, Exercice, Exercice, Exercice, Exercice, Exercice, Exercice, Exercice, Exercice, Exercice?)>
<!ATTLIST examen code_cours NMTOKEN #REQUIRED>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date annee NMTOKEN #REQUIRED
               mois (Janvier | Fevrier | Mars | Avril | Mai | Juin | Juillet | Aout | Septembre | Octobre | Novembre | Decembre) #REQUIRED>
<!ELEMENT classe (#PCDATA)>
<!ELEMENT matiere (#PCDATA)>
<!ELEMENT prof (nom, prenom)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT Exercice (description?, question+)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT question (#PCDATA | question)*>

=== Cheikh785/Gestion_fichier_xml/examen/Examen_du_26-07-22-11-24-19.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "../xml/exo6.dtd">
<examen code_cours="115">
<classe>3eme</classe><matiere>Math</matiere><prof><nom>Diagne</nom><prenom>Sira</prenom></prof><date annee="2022" mois="Juillet">2022-07-29</date><Exercice><description>L ,   O ,   U  sont trois points non alignés du plan.  S  est le milieu du segment  [ O U ] .</description><question>Construis le point I tel que : →LI=→LO+→LU</question><question>Démontre que :  →LO+→LU=2→LS&#13;
</question></Exercice><Exercice><description>Soit  R S U  un triangle rectangle en  U  tel que  R S = 3   et  S U = 2</description><question> ABC est  un triangle rectangle en A tel que ˆABC=56o et BC=4.2cm. Calculer AB et  AC</question><question>Construire un triangle OIE rectangle en O tel que ˆOEI=72o et OE=2cm. Calculer l'arrondi au dixième près de OI et vérifier sur la figure.</question></Exercice><Exercice><description>A B C D   est un trapèze de bases  ( A B )  et  ( D C )  ;  A B = 3 c m ;   B C = 4 c m ;   D C = 5 c m  et  ˆ B C D = 60 ∘ .   La parallèle à  ( B C )  passant par  A  coupe  ( B D )  en  I  et  ( D C )  en  M .</description><question> Faire la figure.</question><question>Quelle est la nature du quadrilatère ABCM ? En déduire MC puis AI.</question><question>Soit P un point de [BC] tel que PC=2.4. Montrer que les droites (MP) et (DB)sont parallèles.</question></Exercice><Exercice><description>Voici les tailles en cm des vingt élèves d'une classe de 3iéme. 165 145 150 166 165 160 158 162 165 150 158 165 154 158 160 162 162 154 165 160</description><question> a) Quelle est la population étudiée ? &#13;
 &#13;
b) Quelle est le caractère étudié ? Puis donner sa nature.</question><question>Dresser le tableau des : Effectifs ; ECC ; ECD ; Fréquences ; FCC et FCD en %&#13;
.</question><question>a) Combien d'élèves ont au plus 158cm?&#13;
&#13;
 b) Combien d'élèves ont plus de 158cm ?</question><question>a) Quel est le mode de cette série ? Donner sa signification.&#13;
 &#13;
b) Calculer la taille moyenne de cette série. Donner sa signification.</question></Exercice><Exercice><description>exercice</description><question>question</question></Exercice><Exercice><description>exercice</description><question>question</question></Exercice><Exercice><description>exercice</description><question>question</question></Exercice><Exercice><description>exercice</description><question>question</question></Exercice><Exercice><description>exercice</description><question>question</question></Exercice><Exercice><description>exercice</description><question>question</question></Exercice></examen>

=== Cheikh785/Gestion_fichier_xml/examen/Examen_du_26-07-22-05-05-24.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "../xml/exo6.dtd">
<examen code_cours="info 114">
<classe>dic3</classe><matiere>XML</matiere><prof><nom>Camara</nom><prenom>Ibrahima</prenom></prof><date annee="2022" mois="Juillet">2022-07-27</date><Exercice><description>exercice</description><question>question numero un</question><question>question numero deux</question><question>question numero 3</question></Exercice><Exercice><description>exercice</description><question>question numero un</question><question>question numero deux</question></Exercice><Exercice><description/><question>question numero un</question><question>question numero deux</question></Exercice><Exercice><description/><question>question numero un</question></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice></examen>

=== Cheikh785/Gestion_fichier_xml/examen/Examen_du_25-07-22-04-20-42.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "../xml/exo6.dtd">
<examen code_cours="info 114">
<classe>dic3</classe><matiere>IA</matiere><prof><nom>Camara</nom><prenom>Mamadou Samba</prenom></prof><date annee="2022" mois="Juillet">2022-07-27</date><Exercice><description>exercice</description><question>(#PCDATA)(#PCDATA)(#PCDATA)</question></Exercice><Exercice><description>exercice</description><question>(#PCDATA)(#PCDATA)(#PCDATA)</question><question>(#PCDATA)(#PCDATA)(#PCDATA)</question><question>(#PCDATA)(#PCDATA)(#PCDATA)</question></Exercice><Exercice><description>exercice</description><question>(#PCDATA)(#PCDATA)(#PCDATA)</question><question>(#PCDATA)(#PCDATA)(#PCDATA)</question></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice></examen>

=== Cheikh785/Gestion_fichier_xml/examen/Examen_du_25-07-22-03-51-37.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "../xml/exo6.dtd">
<examen code_cours="">
<classe/><matiere/><prof><nom/><prenom/></prof><date annee="" mois=""/><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice><Exercice><description/><question/></Exercice></examen>

=== Cheikh785/Gestion_fichier_xml/examen/Examen_du_25-07-22-03-33-18.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "../xml/exo6.dtd">
<examen code_cours="info 112">
<classe>dic2</classe><matiere>XML</matiere><prof><nom>Fall</nom><prenom>Ibrahima</prenom></prof><date annee="2022" mois="Juillet">2022-07-25</date><Exercice><description>exercice</description><question>ceci est la question numero 1</question><question>ceci est la question numero 2</question><question>ceci est la question numero 3</question></Exercice><Exercice><description>exercice</description><question>ceci est la question numero 1</question><question>ceci est la question numero 2</question></Exercice><Exercice><description>exercice</description><question>ceci est la question numero 1</question></Exercice><Exercice><description>exercice</description><question>ceci est la question numero 1</question></Exercice><Exercice><description/><question>ceci est la question numero 1</question></Exercice><Exercice><description/><question>ceci est la question numero 1</question></Exercice><Exercice><description/><question>ceci est la question numero 1</question></Exercice><Exercice><description/><question>ceci est la question numero 1</question></Exercice><Exercice><description/><question>ceci est la question numero 1</question></Exercice><Exercice><description/><question>ceci est la question numero 1</question></Exercice></examen>
